version: '3.9'

services:
  db-postgres:
    container_name: db-postgres
    image: postgres:15.6-bullseye
    restart: on-failure
    environment:
      - POSTGRES_HOST=${POSTGRES_SERVER_URL}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_SERVER_PORT}:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  cache-redis:
    container_name: cache-redis
    image: redis:7-alpine
    restart: on-failure
    ports:
      - ${REDIS_SERVER_PORT}:6379
    command: --requirepass ${REDIS_PASSWORD}
